version: '3'

services:
  web:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - mongodb
      - qdrant

  mongodb:
    image: mongo
    ports:
      - "27017:27017"

  qdrant:
    image: qdrant/qdrant
    ports:
      - "6333:6333"

  frontend:
    build: ./app
    command: streamlit run streamlit_app.py
    ports:
      - "8501:8501"
    depends_on:
      - web
